### PR TITLE
add babashka.http-client

### PR DESCRIPTION
**Pull request by jasalt**

### CODE REVIEW

**Comment by jasalt** [comment]
Maybe could add also info indicator or something to this entry or to `babashka.curl` about this being more current choice, eventhough that is very clearly explained on `babashka.curl` GH project page readme.

**Comment by borkdude** [comment]
You can add `platforms: [built-in]` since bb.http-client is built-in
Good idea about bb.curl

**Comment by jasalt** [comment]
@borkdude indeed. I added those.

**Comment by borkdude** [comment]
Thanks!

**Pull request merged**
