### PR TITLE
Add tick

### PR DESCRIPTION
**Pull request by jasalt**
Support added 23/03 https://github.com/juxt/tick/pull/179

### CODE REVIEW

**Comment by borkdude** [comment]
Oh I didn't realize you edited the generated HTML rather than the data source itself.

**Comment by borkdude** [comment]
Fixed

**Comment by jasalt** [comment]
@borkdude haha, sorry, did not realise how that worked. Anyways, seems it got a duplicated the section now: 

Screenshot_20240612_063009

**Comment by borkdude** [comment]
Should be fixed now I think, thanks :)

**Pull request merged**
